name: Build LaTeX document
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile Manuscript
        uses: xu-cheng/latex-action@v2
        with:
          root_file: manuscript/main.tex
          work_in_root_file_dir: true
      - name: Compile Figures
        uses: xu-cheng/latex-action@v2
        with:
          root_file: slides/figures.tex
          work_in_root_file_dir: true
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDFs
          path: |
            manuscript/main.pdf
            slides/figures.pdf
